# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      aws_access_key_dev: ${{secrets.AWS_DEV_ACCESS_KEY}}
      aws_secret_key_dev: ${{secrets.AWS_DEV_SECRET_KEY}}
      aws_access_key_demo: ${{secrets.AWS_DEMO_ACCESS_KEY}}
      aws_secret_key_demo: ${{secrets.AWS_DEMO_SECRET_KEY}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build Artifact
        run: |
          mvn clean install
          cd target

      - name: Zip Artifact
        run: echo "current build number is "
          pwd
          mkdir -p codedeploy_artifact
          cd codedeploy_artifact
          cp ../pom.xml .
          cp ../target/webapp-0.0.1-SNAPSHOT.jar .
          cp ../src/main/resources/*.properties .
          zip -r csye6225-web-app.zip .
          rm *.xml *.properties *.jar
          ls -al
          pwd
          cd ..
          pwd

      - name: Install awscli
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Terraform Apply
        run: |
          cd aws-infra-main
          cd packer 
          packer build -var "aws_access_key=${aws_access_key_dev}" -var "aws_secret_key=${aws_secret_key_dev}" ami.json 
          cd ..
          terraform init
          terraform apply -var" aws_access_key=${aws_access_key_demo}" -var "aws_secret_key=${aws_secret_key_demo}"

      - name: Set Environment Variables
        env:
          bucket_name: ${{ steps.apply.outputs.bucket_name }}
          private_key: ${{ steps.apply.outputs.private_key }}
          public_key: ${{ steps.apply.outputs.public_key }}
          region: ${{ steps.apply.outputs.region }}
        run: |
          echo "Bucket Name: $bucket_name"
          echo "Private Key: $private_key"
          echo "Public Key: $public_key"
          echo "Region: $region"

      - name: Upload Artifact To S3
        run: echo "Uploading to S3 bucket"
          cd codedeploy_artifact
          aws s3 cp csye6225-webapp.zip s3://${bucket_name}

      - name: Make CodeDeploy API call
        run: echo "CodeDeploy"
          aws deploy register-application-revision --region ${region} --application-name csye6225-webapp \
          --s3-location bucket=${bucket_name},key=csye6225-webapp.zip,bundleType=zip
          echo "------------------------------------------------------"
          aws deploy list-application-revisions --region ${region} --application-name csye6225-webapp \
          --s-3-bucket code-deploy.csye6225-su19-sebastianc.me --deployed exclude
          echo "------------------------------------------------------"
          deploymentId=$(aws deploy create-deployment --region ${region} \
          --application-name csye6225-webapp \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name csye6225-webapp-deployment \
          --s3-location bucket=${bucket_name},bundleType=zip,key=csye6225-webapp.zip \
          --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE,DEPLOYMENT_STOP_ON_ALARM,DEPLOYMENT_STOP_ON_REQUEST)
          echo "$deploymentId"
