# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#          cd aws-infra-main
#          cd packer
#          packer build -var "aws_access_key=${aws_access_key_dev}" -var "aws_secret_key=${aws_secret_key_dev}" ami.json
#          cd ..

name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      aws_access_key_dev: ${{secrets.AWS_DEV_ACCESS_KEY}}
      aws_secret_key_dev: ${{secrets.AWS_DEV_SECRET_KEY}}
      ssh_public: ${{secrets.SSH_PUB}}
      ssh_private: ${{secrets.SSH_PRIVATE}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build Artifact
        run: |
          mvn clean install
          cd target

      - name: Zip Artifact
        run: echo "current build number is "
          pwd
          mkdir -p codedeploy_artifact
          cd codedeploy_artifact
          cp ../pom.xml .
          cp ../target/webapp-0.0.1-SNAPSHOT.jar .
          cp ../src/main/resources/*.properties .
          zip -r csye6225-web-app.zip .
          rm *.xml *.properties *.jar
          ls -al
          pwd
          cd ..
          pwd

      - name: Install awscli
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Install SSH
        run: sudo apt-get install -y ssh

      - name: Configure AWS credentials
        env:
          aws_access_key_demo: ${{secrets.AWS_DEMO_ACCESS_KEY}}
          aws_secret_key_demo: ${{secrets.AWS_DEMO_SECRET_KEY}}
        run: |
          aws configure set aws_access_key_id $aws_access_key_demo --profile demo
          aws configure set aws_secret_access_key $aws_secret_key_demo --profile demo
      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUB}}

        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2
          chmod 600 ~/.ssh/ec2
          echo "$SSH_KNOWN_HOSTS_PROD" > ~/.ssh/known_hosts.old

      - name: Terraform Apply
        id: terraform-apply
        run: |
          cd aws-infra-main
          cd packer
          packer build -var "aws_access_key=${aws_access_key_dev}" -var "aws_secret_key=${aws_secret_key_dev}" ami.json
          cd ..
          terraform init
          terraform destroy -auto-approve -var "aws_access_key=${aws_access_key_demo}" -var "aws_secret_key=${aws_secret_key_demo}" 
          terraform apply -auto-approve -var "aws_access_key=${aws_access_key_demo}" -var "aws_secret_key=${aws_secret_key_demo}" 
          INSTANCE_PUBLIC_IP=$(terraform output public_ip | tr -d '"')
          echo "ip=${INSTANCE_PUBLIC_IP}" >> $GITHUB_ENV

      - name: Wait 2 minutes
        run: sleep 2m

      - name: Copy file to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{env.ip}}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Private key stored in GitHub secrets
          port: 22
          source: codedeploy_artifact/csye6225-web-app.zip
          target: ~/ # Destination directory in the remote server

      - name: Extract Java ZIP file on EC2 instance
        run: |
          ssh -i ~/.ssh/ec2 -o UserKnownHostsFile=~/.ssh/known_hosts.old -o StrictHostKeyChecking=no -tt ec2-user@${{env.ip}} "unzip -o /home/ec2-user/csye6225-web-app.zip -d /usr/local/tomcat/webapps"
      - name: Start application on EC2 using screen
        run: |
          ssh -i ~/.ssh/ec2 -o UserKnownHostsFile=~/.ssh/known_hosts.old -o StrictHostKeyChecking=no -tt ec2-user@${{env.ip}} "screen -dmS csye6225-web-app java -jar /usr/local/tomcat/webapps/webapp-0.0.1-SNAPSHOT.jar"
